spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.example.model

server:
  port: 8080